apiVersion: v1
kind: Pod
metadata:
  name: ecr-pod
spec:
  containers:
  - name: ecr-container
    image: 791532114280.dkr.ecr.us-east-1.amazonaws.com/sch-build-agent:sch-sit2-final234
    resources:
        limits:
          cpu: "500m"
          memory: "12Gi"
        requests:
          cpu: "500m"
          memory: "12Gi"
    workingDir: /home/node/jenkins 
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: "/home/node/jenkins"
        name: "workspace-volume"
        readOnly: false
