apiVersion: v1
kind: Service
metadata:
  name: dh-docs-service
  namespace: {{ .Values.namespaces.application }}
  {{ if .Values.internal_load_balancer }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  {{ end }}
spec:
  type: {{ .Values.docs.service.type }}
  ports:
    - port: 80
      targetPort: 8000
  selector:
    name: dh-docs
